//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroDeClientes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public int id_cliente { get; set; }

        [Required(ErrorMessage = "* Campo requerido")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "* Campo requerido")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "* Campo requerido")]
        [DataType(DataType.PhoneNumber)]
        public string Telefono { get; set; }

        [Required(ErrorMessage = "* Campo requerido")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    }
}
